export type IndustryExperience = {
  id: string;
  label: string;
  aliases: string[];
  category: string;
  headline: string;
  subheadline: string;
  deskName: string;
  problem: string;
  outcome: string;
  services: string[];
  qualificationQuestions: string[];
  urgentKeywords: string[];
  fitKeywords: string[];
  leakTypes: string[];
  assistantRole: string;
  customerMessage: string;
  assistantReply: string;
  signalLabels: [string, string, string];
};

export const INDUSTRY_EXPERIENCES: IndustryExperience[] = [
  {
    id: "plumber",
    label: "Plumbing",
    aliases: ["plumber", "plumbing"],
    category: "Home & field services",
    headline: "Turn plumbing enquiries into booked jobs.",
    subheadline: "RevenueDesk answers geyser, leak, drain and emergency plumbing enquiries while you are on the tools.",
    deskName: "Plumbing Revenue Desk",
    problem: "Burst pipes, geysers and blocked drains do not wait for the owner to finish the current job.",
    outcome: "Every plumbing enquiry is captured, qualified by suburb and urgency, and pushed towards a booking.",
    services: ["Emergency plumbing", "Geyser repairs", "Leak detection", "Blocked drains", "Bathroom and kitchen plumbing"],
    qualificationQuestions: ["What plumbing problem do you need help with?", "Which suburb are you in?", "How urgent is it — now, today, or later?", "Is this a home, rental, office or commercial property?"],
    urgentKeywords: ["burst", "flood", "flooding", "overflow", "no water", "emergency", "urgent", "leaking now", "geyser"],
    fitKeywords: ["plumb", "leak", "geyser", "drain", "pipe", "toilet", "tap"],
    leakTypes: ["Burst or urgent enquiry waiting", "Geyser enquiry not followed up", "Quote for repair or replacement going cold"],
    assistantRole: "plumbing front-desk assistant",
    customerMessage: "Hi, our geyser burst in Fourways. Can someone come today?",
    assistantReply: "Yes, we can help. Are you still getting water from the geyser, and what suburb are you in exactly?",
    signalLabels: ["Problem", "Urgency", "Area"],
  },
  {
    id: "electrician",
    label: "Electrical",
    aliases: ["electrician", "electrical", "electrical contractor"],
    category: "Home & field services",
    headline: "Keep electrical enquiries moving while your team is on site.",
    subheadline: "RevenueDesk qualifies faults, DB boards, installations and COCs before the customer goes elsewhere.",
    deskName: "Electrical Revenue Desk",
    problem: "Electrical teams are often driving or working at a board when the next enquiry arrives.",
    outcome: "Customers get a fast response, the fault is qualified, and the right job reaches the right person.",
    services: ["Fault finding", "DB board repairs and upgrades", "Electrical installations", "COCs", "Solar and inverter electrical work"],
    qualificationQuestions: ["What electrical issue or job do you need help with?", "Which suburb are you in?", "Is there immediate danger or a power outage?", "Is it residential or commercial?"],
    urgentKeywords: ["sparking", "smoke", "fire", "power out", "short circuit", "danger", "emergency", "urgent"],
    fitKeywords: ["electric", "power", "db board", "coc", "solar", "inverter", "wiring", "lights"],
    leakTypes: ["Dangerous fault waiting for a response", "Installation quote going cold", "COC enquiry not converted"],
    assistantRole: "electrical front-desk assistant",
    customerMessage: "Hi, the DB board keeps tripping and we have no power.",
    assistantReply: "I can help get this to the electrician. Is there any smoke, burning smell or sparking, and which suburb are you in?",
    signalLabels: ["Fault", "Safety", "Area"],
  },
  {
    id: "security",
    label: "Security",
    aliases: ["security", "security company", "armed response", "cctv", "alarm", "guarding"],
    category: "Property & protection",
    headline: "Turn security enquiries into site surveys and contracts.",
    subheadline: "RevenueDesk qualifies CCTV, alarms, electric fencing, guarding and armed-response enquiries before they disappear.",
    deskName: "Security Revenue Desk",
    problem: "Security enquiries usually need property details, existing systems and site information before a quote.",
    outcome: "RevenueDesk captures the property, security problem and service required so sales can move faster.",
    services: ["CCTV", "Alarm systems", "Electric fencing", "Access control", "Armed response", "Guarding"],
    qualificationQuestions: ["Is this residential, estate or commercial?", "Which suburb and property type is this?", "What security do you need — CCTV, alarm, fencing, access control or response?", "Do you already have an installed system?"],
    urgentKeywords: ["break-in", "burglary", "alarm", "intruder", "urgent", "armed response", "crime", "broken fence"],
    fitKeywords: ["security", "cctv", "camera", "alarm", "fence", "fencing", "access control", "armed response", "guard"],
    leakTypes: ["Security installation enquiry waiting for a survey", "Quote not followed up", "Urgent security incident without a human handover"],
    assistantRole: "security front-desk assistant",
    customerMessage: "We need CCTV and electric fencing for a house in Sandton.",
    assistantReply: "Absolutely. Is the property a house or estate, and do you already have an alarm or access-control system?",
    signalLabels: ["Property", "Security need", "Existing system"],
  },
  {
    id: "solar",
    label: "Solar / Inverter",
    aliases: ["solar", "solar installer", "inverter", "battery", "backup power"],
    category: "Home & field services",
    headline: "Qualify high-value solar enquiries before the quote stage.",
    subheadline: "RevenueDesk captures the property, power problem, load needs and urgency behind every solar or backup-power enquiry.",
    deskName: "Solar Revenue Desk",
    problem: "Solar customers ask many questions before they buy, and slow follow-up can turn a high-value enquiry cold.",
    outcome: "RevenueDesk moves each enquiry toward the right site assessment, quote or consultation.",
    services: ["Solar PV", "Inverters", "Battery backup", "Load-shedding solutions", "System upgrades"],
    qualificationQuestions: ["Is this a home, office or other property?", "Which suburb are you in?", "What are you trying to keep powered during outages?", "Do you already have solar, an inverter or batteries?"],
    urgentKeywords: ["load shedding", "no power", "backup", "urgent", "inverter fault", "battery fault"],
    fitKeywords: ["solar", "inverter", "battery", "backup", "panels", "pv", "load shedding"],
    leakTypes: ["High-value solar enquiry not followed up", "Site assessment waiting to be booked", "Quote going cold after technical questions"],
    assistantRole: "solar sales front-desk assistant",
    customerMessage: "I want an inverter and batteries for my house in Bryanston.",
    assistantReply: "We can help. Which appliances do you need to keep running during outages, and do you already have any solar or backup equipment?",
    signalLabels: ["Property", "Load", "Existing system"],
  },
  {
    id: "auto-workshop",
    label: "Auto Workshop",
    aliases: ["auto repair", "workshop", "mechanic", "automotive", "auto workshop"],
    category: "Automotive",
    headline: "Turn vehicle problems into booked workshop jobs.",
    subheadline: "RevenueDesk captures the car, fault, urgency and location while your technicians keep working.",
    deskName: "Auto Workshop Revenue Desk",
    problem: "Workshops lose enquiries when technicians cannot answer while they are under a vehicle.",
    outcome: "Customers arrive with the right information, and quotes and follow-ups do not sit forgotten.",
    services: ["Diagnostics", "Servicing", "Brake repairs", "Engine repairs", "Pre-purchase inspections"],
    qualificationQuestions: ["What vehicle make, model and year is it?", "What problem is the vehicle having?", "Can it still drive?", "Which suburb are you in?"],
    urgentKeywords: ["breakdown", "stranded", "won't start", "wont start", "immobile", "accident", "urgent"],
    fitKeywords: ["car", "bakkie", "vehicle", "mechanic", "battery", "brake", "engine", "service", "diagnostic"],
    leakTypes: ["Breakdown enquiry waiting", "Repair quote not approved", "Service enquiry not converted to a booking"],
    assistantRole: "automotive front-desk assistant",
    customerMessage: "My Polo won't start in Randburg. Can you come out?",
    assistantReply: "We can help. What year and engine is the Polo, and is it parked at home, work or on the roadside?",
    signalLabels: ["Vehicle", "Problem", "Location"],
  },
  {
    id: "mobile-mechanic",
    label: "Mobile Mechanic",
    aliases: ["mobile mechanic", "mobile auto"],
    category: "Automotive",
    headline: "Respond before the stranded customer calls the next mechanic.",
    subheadline: "RevenueDesk handles breakdown details, vehicle information and location while the mechanic is driving.",
    deskName: "Mobile Mechanic Revenue Desk",
    problem: "Roadside customers need an answer now, often while the mechanic is already with another vehicle.",
    outcome: "RevenueDesk captures the essentials and gets urgent jobs to the right human fast.",
    services: ["Breakdown assistance", "Diagnostics", "Battery and starting faults", "Brake repairs", "Mobile servicing"],
    qualificationQuestions: ["What vehicle make, model and year is it?", "Where is the vehicle right now?", "What happened?", "Can the vehicle still drive?"],
    urgentKeywords: ["breakdown", "stranded", "won't start", "wont start", "immobile", "urgent", "roadside"],
    fitKeywords: ["mobile mechanic", "car", "vehicle", "battery", "breakdown", "roadside", "engine"],
    leakTypes: ["Roadside enquiry waiting", "Location missing from an urgent job", "Breakdown lead lost after first contact"],
    assistantRole: "roadside-assistance front-desk assistant",
    customerMessage: "I'm stranded with a dead battery on William Nicol.",
    assistantReply: "I can get the right person moving. What vehicle are you in, and which direction or nearest landmark are you at?",
    signalLabels: ["Vehicle", "Urgency", "Location"],
  },
  {
    id: "towing",
    label: "Towing / Roadside",
    aliases: ["towing", "tow truck", "roadside assistance", "recovery"],
    category: "Automotive",
    headline: "Never make a stranded driver wait for a callback.",
    subheadline: "RevenueDesk captures location, vehicle, incident and destination so a tow can be dispatched faster.",
    deskName: "Towing Revenue Desk",
    problem: "Roadside enquiries are urgent and often arrive after hours, when the dispatcher is already busy.",
    outcome: "RevenueDesk collects dispatch-ready information immediately.",
    services: ["Vehicle towing", "Breakdown recovery", "Accident recovery", "Battery assistance", "Roadside assistance"],
    qualificationQuestions: ["Where is the vehicle right now?", "What vehicle is it?", "What happened?", "Where does the vehicle need to go?"],
    urgentKeywords: ["accident", "stranded", "breakdown", "tow", "urgent", "roadside", "stuck"],
    fitKeywords: ["tow", "towing", "recovery", "roadside", "breakdown", "vehicle", "accident"],
    leakTypes: ["Urgent roadside enquiry waiting", "Location not captured", "Dispatch request not acknowledged"],
    assistantRole: "roadside dispatch front-desk assistant",
    customerMessage: "I need a tow from Midrand to a panel beater.",
    assistantReply: "I can help with the dispatch details. Where exactly is the vehicle, and what make and model is it?",
    signalLabels: ["Location", "Vehicle", "Destination"],
  },
  {
    id: "hvac",
    label: "Aircon / HVAC",
    aliases: ["hvac", "aircon", "air conditioning", "refrigeration"],
    category: "Home & field services",
    headline: "Turn aircon faults and installation requests into booked visits.",
    subheadline: "RevenueDesk qualifies cooling problems, property type and urgency while the technician is on site.",
    deskName: "HVAC Revenue Desk",
    problem: "Aircon and refrigeration teams are often moving between sites when new enquiries arrive.",
    outcome: "Each enquiry is qualified for repair, installation, maintenance or replacement.",
    services: ["Aircon repairs", "Aircon installation", "Maintenance", "Commercial HVAC", "Refrigeration"],
    qualificationQuestions: ["Is this a repair, installation or maintenance enquiry?", "Which suburb or site are you in?", "What equipment or room is affected?", "Is the unit completely down or still running?"],
    urgentKeywords: ["not cooling", "leaking", "hot", "broken", "down", "urgent", "refrigeration"],
    fitKeywords: ["aircon", "air conditioning", "hvac", "cooling", "refrigeration", "compressor"],
    leakTypes: ["Repair enquiry waiting for diagnosis", "Installation quote not followed up", "Commercial HVAC enquiry going cold"],
    assistantRole: "HVAC front-desk assistant",
    customerMessage: "Our office aircon is not cooling and we have 20 staff.",
    assistantReply: "We can help. What area is the office in, and is the unit running but not cooling or completely off?",
    signalLabels: ["Problem", "Property", "Urgency"],
  },
  {
    id: "roofing-waterproofing",
    label: "Roofing / Waterproofing",
    aliases: ["roofing", "roofer", "waterproofing", "roof repair"],
    category: "Property & field services",
    headline: "Turn roof leaks into inspections and quotes.",
    subheadline: "RevenueDesk captures roof problems, property location, photos and timing before the customer moves on.",
    deskName: "Roofing Revenue Desk",
    problem: "Roofing jobs are visual, location-dependent and high-value, so slow qualification costs real opportunities.",
    outcome: "Customers get a useful first response and the team gets inspection-ready information.",
    services: ["Roof repairs", "Waterproofing", "Leak detection", "Roof maintenance", "Roof replacement"],
    qualificationQuestions: ["What is happening with the roof?", "Which suburb is the property in?", "Is water entering the building now?", "Can you send photos of the affected area?"],
    urgentKeywords: ["leak", "flood", "rain", "water coming in", "storm", "urgent", "ceiling"],
    fitKeywords: ["roof", "roofing", "waterproof", "leak", "ceiling", "gutter"],
    leakTypes: ["Storm or active leak enquiry waiting", "Inspection not booked", "Roof replacement quote going cold"],
    assistantRole: "roofing front-desk assistant",
    customerMessage: "Water is coming through the ceiling after last night's rain.",
    assistantReply: "We can help. Which suburb is the property in, and can you send a photo of the ceiling and roof area if it is safe to do so?",
    signalLabels: ["Problem", "Area", "Evidence"],
  },
  {
    id: "gates-access",
    label: "Gates / Electric Fencing / Access Control",
    aliases: ["gate motors", "electric fencing", "access control", "gates", "gate automation"],
    category: "Property & protection",
    headline: "Convert security-installation enquiries into site visits.",
    subheadline: "RevenueDesk qualifies gate, fence, intercom and access-control jobs before the installer calls back.",
    deskName: "Access Control Revenue Desk",
    problem: "Installers need property and system details before pricing, but those details are often missing from first contact.",
    outcome: "RevenueDesk collects the information needed to schedule the right visit.",
    services: ["Gate motors", "Electric fencing", "Intercoms", "Access control", "Repairs"],
    qualificationQuestions: ["What security or access-control problem do you have?", "Which suburb is the property in?", "Is there an existing gate motor or fence?", "Is this a repair or a new installation?"],
    urgentKeywords: ["broken gate", "gate stuck", "fence down", "urgent", "security risk", "intruder"],
    fitKeywords: ["gate", "fence", "electric fence", "access control", "intercom", "motor"],
    leakTypes: ["Security-risk repair waiting", "Site survey not booked", "Installation quote going cold"],
    assistantRole: "access-control front-desk assistant",
    customerMessage: "Our gate motor has stopped working and the gate is stuck open.",
    assistantReply: "We can help. Which suburb are you in, and is the gate currently stuck open, closed or partially open?",
    signalLabels: ["Fault", "Security risk", "Area"],
  },
  {
    id: "pest-control",
    label: "Pest Control",
    aliases: ["pest control", "pest", "fumigation"],
    category: "Home & field services",
    headline: "Turn pest complaints into booked treatments.",
    subheadline: "RevenueDesk identifies the pest, property type, severity and timing before the technician arrives.",
    deskName: "Pest Control Revenue Desk",
    problem: "Customers usually want reassurance and a quick solution, while technicians need basic property details before quoting.",
    outcome: "RevenueDesk converts urgent pest complaints into qualified treatment bookings.",
    services: ["Cockroach treatment", "Rodent control", "Termite treatment", "Fumigation", "Recurring pest management"],
    qualificationQuestions: ["What pest are you dealing with?", "Which suburb is the property in?", "Is this a home, office, restaurant or other property?", "How widespread is the problem?"],
    urgentKeywords: ["infestation", "rats", "rodents", "termites", "cockroaches", "urgent", "restaurant"],
    fitKeywords: ["pest", "cockroach", "rat", "rodent", "termite", "fumigation", "infestation"],
    leakTypes: ["Urgent treatment enquiry waiting", "Inspection not booked", "Recurring-service opportunity missed"],
    assistantRole: "pest-control front-desk assistant",
    customerMessage: "We have cockroaches in our restaurant in Rosebank.",
    assistantReply: "We can help. Is the problem mainly in the kitchen, dining area or both, and when was it first noticed?",
    signalLabels: ["Pest", "Property", "Severity"],
  },
  {
    id: "property-maintenance",
    label: "Property Maintenance",
    aliases: ["property maintenance", "maintenance", "handyman", "facilities services"],
    category: "Property & field services",
    headline: "Turn maintenance requests into work orders and quotes.",
    subheadline: "RevenueDesk sorts repairs, inspections and recurring maintenance enquiries while your team is moving between sites.",
    deskName: "Property Maintenance Revenue Desk",
    problem: "Maintenance teams receive mixed requests across WhatsApp and phone and lose jobs when requests are not prioritised.",
    outcome: "Every request arrives with property, issue, urgency and access information.",
    services: ["General maintenance", "Repairs", "Inspections", "Property make-ready", "Recurring maintenance"],
    qualificationQuestions: ["What needs to be repaired or maintained?", "Which property is this?", "How urgent is it?", "Who provides access to the property?"],
    urgentKeywords: ["water leak", "no power", "broken", "urgent", "tenant", "emergency"],
    fitKeywords: ["maintenance", "repair", "property", "handyman", "facility", "tenant"],
    leakTypes: ["Tenant repair waiting", "Quote not followed up", "Recurring maintenance opportunity missed"],
    assistantRole: "property-maintenance front-desk assistant",
    customerMessage: "The tenant has reported a leaking tap at our Randburg property.",
    assistantReply: "I can log the repair. What is the property address, and is the leak minor or is water currently running?",
    signalLabels: ["Issue", "Property", "Urgency"],
  },
  {
    id: "pool",
    label: "Pool",
    aliases: ["pool", "pool service", "pool maintenance", "pool renovation"],
    category: "Property & field services",
    headline: "Turn pool enquiries into service, repair and renovation jobs.",
    subheadline: "RevenueDesk separates maintenance, equipment faults and renovation opportunities so high-value pool enquiries do not disappear.",
    deskName: "Pool Revenue Desk",
    problem: "Pool businesses often have a mix of small maintenance requests and much larger renovation or equipment opportunities.",
    outcome: "RevenueDesk identifies the real job behind the message and keeps follow-up moving.",
    services: ["Pool maintenance", "Pump repairs", "Filtration", "Renovation", "New pool installation"],
    qualificationQuestions: ["What is happening with the pool?", "Which suburb is the property in?", "Is this maintenance, a repair or a renovation?", "What pool equipment is already installed?"],
    urgentKeywords: ["green", "leak", "pump broken", "filter broken", "urgent"],
    fitKeywords: ["pool", "pump", "filter", "chlorine", "renovation", "fibreglass"],
    leakTypes: ["Equipment repair waiting", "Quote for renovation going cold", "Replacement opportunity missed"],
    assistantRole: "pool-service front-desk assistant",
    customerMessage: "The pool is green and the pump has stopped working.",
    assistantReply: "We can help. Which suburb are you in, and has the pump stopped completely or is it making a noise but not circulating water?",
    signalLabels: ["Problem", "Equipment", "Area"],
  },
  {
    id: "dental",
    label: "Dental",
    aliases: ["dentist", "dental", "dental practice", "orthodontist", "implant"],
    category: "Health & high-value appointments",
    headline: "Turn dental enquiries into booked consultations.",
    subheadline: "RevenueDesk handles first response, service questions and appointment qualification while the practice team stays focused on patients.",
    deskName: "Dental Revenue Desk",
    problem: "Patients often enquire after hours and compare several practices before booking.",
    outcome: "RevenueDesk answers approved questions, identifies treatment intent and moves patients toward an appointment.",
    services: ["General dentistry", "Cosmetic dentistry", "Implants", "Orthodontics", "Emergency dentistry"],
    qualificationQuestions: ["What treatment or dental problem are you enquiring about?", "Is this an emergency or planned treatment?", "Have you visited a dentist about it before?", "What day or time would suit you for a consultation?"],
    urgentKeywords: ["toothache", "pain", "swelling", "bleeding", "broken tooth", "emergency", "urgent"],
    fitKeywords: ["dentist", "dental", "tooth", "implant", "braces", "orthodontic", "cosmetic"],
    leakTypes: ["New patient enquiry waiting", "Treatment consultation not booked", "High-value treatment enquiry going cold"],
    assistantRole: "dental practice front-desk assistant",
    customerMessage: "I need an implant consultation and I am in Sandton.",
    assistantReply: "We can help with that. Are you looking for a single implant or replacing multiple teeth, and what day would suit you for a consultation?",
    signalLabels: ["Treatment", "Intent", "Appointment"],
  },
  {
    id: "aesthetics",
    label: "Aesthetics / Cosmetic Clinic",
    aliases: ["aesthetics", "aesthetic clinic", "cosmetic clinic", "botox", "fillers", "skin clinic"],
    category: "Health & high-value appointments",
    headline: "Turn treatment enquiries into booked consultations.",
    subheadline: "RevenueDesk responds to treatment questions, qualification and booking requests while your clinicians focus on clients.",
    deskName: "Aesthetics Revenue Desk",
    problem: "Prospective patients compare treatments, prices and availability before committing, often after hours.",
    outcome: "RevenueDesk keeps the enquiry moving without overstepping into clinical advice.",
    services: ["Injectables", "Skin treatments", "Laser", "Hair restoration", "Body treatments"],
    qualificationQuestions: ["Which treatment are you interested in?", "Is this your first consultation with us?", "What result are you hoping to achieve?", "When would you like to come in?"],
    urgentKeywords: ["appointment", "availability", "consultation"],
    fitKeywords: ["botox", "filler", "laser", "skin", "aesthetic", "cosmetic", "hair restoration"],
    leakTypes: ["Treatment enquiry waiting", "Consultation not booked", "Follow-up after consultation missed"],
    assistantRole: "aesthetic clinic front-desk assistant",
    customerMessage: "Hi, I want to know about Botox and pricing in Rosebank.",
    assistantReply: "Happy to help with the treatment information we have approved. Is this your first consultation with us, and would you like us to check appointment availability?",
    signalLabels: ["Treatment", "Customer stage", "Booking"],
  },
  {
    id: "real-estate",
    label: "Real Estate",
    aliases: ["real estate", "estate agent", "property sales", "property agency"],
    category: "Property & high-value sales",
    headline: "Turn property enquiries into qualified viewings.",
    subheadline: "RevenueDesk qualifies buyers and tenants by property, budget, timing and area before routing them to the right agent.",
    deskName: "Property Revenue Desk",
    problem: "Agents are out at viewings while new buyers and tenants keep arriving from property portals and social media.",
    outcome: "Every enquiry gets qualified and routed instead of waiting for an agent to call back.",
    services: ["Property sales", "Property rentals", "Viewings", "Commercial property", "New developments"],
    qualificationQuestions: ["Which property are you enquiring about?", "Are you buying or renting?", "What is your approximate budget?", "When would you like to view?"],
    urgentKeywords: ["viewing", "move in", "offer", "urgent", "available now"],
    fitKeywords: ["property", "house", "apartment", "flat", "rent", "buy", "estate agent", "viewing"],
    leakTypes: ["New property enquiry waiting", "Viewing request not confirmed", "Buyer or tenant going cold after a viewing"],
    assistantRole: "property sales front-desk assistant",
    customerMessage: "Hi, I want to view the house you listed in Bryanston. My budget is R4.5m.",
    assistantReply: "We can help arrange that. Are you buying for yourself or as an investment, and which day would suit you for a viewing?",
    signalLabels: ["Property", "Budget", "Viewing"],
  },
  {
    id: "property-management",
    label: "Property Management",
    aliases: ["property management", "managing agent", "rental management"],
    category: "Property & high-value services",
    headline: "Turn tenant and landlord enquiries into action.",
    subheadline: "RevenueDesk separates maintenance, leasing and owner enquiries so the right person gets the right request.",
    deskName: "Property Management Revenue Desk",
    problem: "Property managers receive a constant mix of tenant issues, owner questions and new leasing enquiries.",
    outcome: "RevenueDesk captures the property, request type and urgency before routing the work.",
    services: ["Residential management", "Commercial management", "Tenant support", "Leasing", "Inspections"],
    qualificationQuestions: ["Are you a tenant, landlord or prospective tenant?", "Which property is this about?", "What is the request or problem?", "How urgent is it?"],
    urgentKeywords: ["water leak", "no power", "lockout", "emergency", "urgent", "tenant"],
    fitKeywords: ["tenant", "landlord", "rental", "property management", "lease", "inspection"],
    leakTypes: ["Tenant maintenance request waiting", "Prospective tenant enquiry not routed", "Landlord request not followed up"],
    assistantRole: "property-management front-desk assistant",
    customerMessage: "I am a tenant and there is a leak in the kitchen.",
    assistantReply: "I can help get this logged. Which property is this, and is water currently running or has the leak stopped?",
    signalLabels: ["Customer type", "Property", "Urgency"],
  },
  {
    id: "legal",
    label: "Law Firm",
    aliases: ["law", "law firm", "attorney", "legal"],
    category: "Professional services",
    headline: "Turn legal enquiries into qualified consultations.",
    subheadline: "RevenueDesk captures matter type, urgency and contact details before the attorney takes over.",
    deskName: "Legal Revenue Desk",
    problem: "Attorneys are rarely available to answer every new enquiry while working on existing matters.",
    outcome: "RevenueDesk collects the basic facts and moves qualified prospects toward a consultation.",
    services: ["Personal injury", "Family law", "Labour law", "Property law", "Commercial disputes"],
    qualificationQuestions: ["What type of legal matter is this?", "Which province or area does the matter relate to?", "Is there a deadline or urgent event?", "Would you like to book a consultation?"],
    urgentKeywords: ["court", "deadline", "summons", "arrest", "eviction", "urgent", "notice"],
    fitKeywords: ["lawyer", "attorney", "legal", "court", "contract", "divorce", "labour", "property"],
    leakTypes: ["New matter enquiry waiting", "Consultation not booked", "High-intent legal enquiry going cold"],
    assistantRole: "legal intake front-desk assistant",
    customerMessage: "I need help with a labour dispute and have a meeting tomorrow.",
    assistantReply: "We can help with the intake. What happened, and is there a formal notice or deadline you need the attorney to know about?",
    signalLabels: ["Matter", "Urgency", "Deadline"],
  },
  {
    id: "financial-broker",
    label: "Financial / Insurance Broker",
    aliases: ["insurance broker", "financial adviser", "mortgage broker", "financial services", "broker"],
    category: "Professional services",
    headline: "Turn financial enquiries into qualified consultations.",
    subheadline: "RevenueDesk captures the product need, customer profile and timing so high-value leads do not disappear in the inbox.",
    deskName: "Financial Revenue Desk",
    problem: "Broker enquiries require qualification and documents, but follow-up often breaks down between first contact and consultation.",
    outcome: "RevenueDesk gets the basics, routes the lead and keeps the next action visible.",
    services: ["Insurance", "Life cover", "Business cover", "Home finance", "Financial planning"],
    qualificationQuestions: ["What are you looking for — insurance, finance or financial advice?", "Is this for you or a business?", "What is the approximate value or cover you need?", "When would you like to speak to an adviser?"],
    urgentKeywords: ["policy", "claim", "renewal", "deadline", "finance", "urgent"],
    fitKeywords: ["insurance", "broker", "finance", "mortgage", "cover", "policy", "adviser"],
    leakTypes: ["Qualified enquiry waiting for adviser", "Document request stalled", "Consultation follow-up missed"],
    assistantRole: "financial-services front-desk assistant",
    customerMessage: "I need business insurance for a construction company in Midrand.",
    assistantReply: "We can help with the initial qualification. What type of construction work do you do, and roughly what level of cover are you looking for?",
    signalLabels: ["Product", "Customer type", "Value"],
  },
  {
    id: "recruitment",
    label: "Recruitment",
    aliases: ["recruitment", "recruiter", "staffing", "labour broker"],
    category: "Professional services",
    headline: "Turn employer and candidate enquiries into qualified opportunities.",
    subheadline: "RevenueDesk separates job requests from candidate enquiries and routes each one with the right information.",
    deskName: "Recruitment Revenue Desk",
    problem: "Recruiters juggle candidate messages, employer vacancies and follow-ups across several channels.",
    outcome: "Every enquiry is tagged, qualified and moved to the next step.",
    services: ["Permanent recruitment", "Contract staffing", "Executive search", "IT recruitment", "Healthcare recruitment"],
    qualificationQuestions: ["Are you hiring or looking for work?", "What role or skill is involved?", "Where is the role or candidate based?", "How soon do you need the position filled?"],
    urgentKeywords: ["urgent hire", "start immediately", "vacancy", "replacement", "deadline"],
    fitKeywords: ["recruiter", "recruitment", "candidate", "vacancy", "hire", "staff", "job"],
    leakTypes: ["Employer enquiry waiting", "Strong candidate not followed up", "Vacancy going cold before shortlist"],
    assistantRole: "recruitment intake front-desk assistant",
    customerMessage: "We need two electricians for a project starting next month.",
    assistantReply: "We can help with the staffing request. Which area is the project in, and what level of experience or certification do the electricians need?",
    signalLabels: ["Request", "Location", "Timing"],
  },
  {
    id: "it-msp",
    label: "IT / MSP / Cybersecurity",
    aliases: ["it", "it support", "msp", "managed services", "cybersecurity", "cyber security"],
    category: "Professional services",
    headline: "Turn technical enquiries into qualified opportunities.",
    subheadline: "RevenueDesk captures the business problem, environment, urgency and scope before the engineer gets involved.",
    deskName: "IT Revenue Desk",
    problem: "Technical teams are busy solving today's issues while tomorrow's enquiries arrive through WhatsApp and web forms.",
    outcome: "RevenueDesk triages support incidents and qualifies new projects without pretending to be the engineer.",
    services: ["Managed IT", "Microsoft 365", "Cybersecurity", "Networks", "Cloud and backup"],
    qualificationQuestions: ["Is this an existing support issue or a new project?", "How many users or devices are involved?", "What is happening right now?", "How urgent is the business impact?"],
    urgentKeywords: ["down", "outage", "ransomware", "hacked", "breach", "urgent", "cannot work"],
    fitKeywords: ["it", "microsoft", "365", "cyber", "security", "network", "server", "cloud", "backup"],
    leakTypes: ["Business-critical support enquiry waiting", "Project lead not qualified", "Proposal follow-up going cold"],
    assistantRole: "IT service-desk and sales-intake assistant",
    customerMessage: "Our Microsoft 365 email is down for 30 staff.",
    assistantReply: "I can capture this for the technical team. Is everyone affected, and can users still sign in to Microsoft 365?",
    signalLabels: ["Issue", "Scale", "Impact"],
  },
  {
    id: "cleaning",
    label: "Cleaning",
    aliases: ["cleaner", "cleaning", "commercial cleaning", "deep cleaning"],
    category: "Property & field services",
    headline: "Turn cleaning enquiries into site visits and bookings.",
    subheadline: "RevenueDesk qualifies the property, cleaning type, timing and frequency while the team is out on jobs.",
    deskName: "Cleaning Revenue Desk",
    problem: "Cleaning businesses miss enquiries when crews are on site and customers need answers quickly.",
    outcome: "Every request arrives with enough detail to price, schedule or inspect.",
    services: ["Home cleaning", "Office cleaning", "Deep cleaning", "Move-in/out", "Post-construction cleaning"],
    qualificationQuestions: ["What type of cleaning do you need?", "Which suburb is the property in?", "When do you need it done?", "Is this once-off or recurring?"],
    urgentKeywords: ["today", "tomorrow", "same day", "urgent", "move out", "move in", "inspection"],
    fitKeywords: ["clean", "office", "home", "deep clean", "move out", "post-construction"],
    leakTypes: ["Cleaning enquiry waiting", "Site visit not booked", "Recurring contract opportunity missed"],
    assistantRole: "cleaning sales front-desk assistant",
    customerMessage: "I need a post-construction clean for a house in Fourways next week.",
    assistantReply: "We can help. Roughly how large is the house, and what day next week would you like the clean completed?",
    signalLabels: ["Service", "Property", "Timing"],
  },
  {
    id: "restoration",
    label: "Restoration",
    aliases: ["restoration", "water damage", "fire restoration", "flood restoration"],
    category: "Property & field services",
    headline: "Respond fast when property damage cannot wait.",
    subheadline: "RevenueDesk captures the incident, location, damage and evidence before the restoration team arrives.",
    deskName: "Restoration Revenue Desk",
    problem: "Water and fire damage create urgent, high-value enquiries that often arrive after hours.",
    outcome: "RevenueDesk captures enough detail for immediate triage and human escalation.",
    services: ["Water damage", "Flood restoration", "Fire restoration", "Mould remediation", "Emergency response"],
    qualificationQuestions: ["What happened — water, fire, mould or another incident?", "Where is the property?", "Is the damage still active?", "Can you safely send photos?"],
    urgentKeywords: ["flood", "burst", "fire", "smoke", "water damage", "emergency", "urgent"],
    fitKeywords: ["restoration", "flood", "fire", "water damage", "mould", "smoke"],
    leakTypes: ["Active damage enquiry waiting", "Emergency call not handed over", "Insurance-related opportunity stalled"],
    assistantRole: "restoration emergency front-desk assistant",
    customerMessage: "A pipe burst and water is running through the ceiling.",
    assistantReply: "We can help urgently. Is the water still running, and which suburb is the property in?",
    signalLabels: ["Incident", "Active damage", "Area"],
  },
  {
    id: "events",
    label: "Wedding / Event Venue",
    aliases: ["wedding venue", "event venue", "conference venue", "events"],
    category: "Hospitality & events",
    headline: "Turn venue enquiries into site visits and signed bookings.",
    subheadline: "RevenueDesk qualifies dates, guest counts, event type and budget while your venue team is hosting.",
    deskName: "Events Revenue Desk",
    problem: "High-value venue enquiries often arrive after hours while the team is busy with an event.",
    outcome: "Every enquiry is qualified for date, size, package and next action.",
    services: ["Weddings", "Corporate events", "Conferences", "Private functions", "Venue hire"],
    qualificationQuestions: ["What type of event are you planning?", "What date are you considering?", "How many guests are you expecting?", "Would you like to view packages or book a site visit?"],
    urgentKeywords: ["date", "availability", "this month", "urgent", "booking"],
    fitKeywords: ["wedding", "venue", "conference", "event", "function", "party"],
    leakTypes: ["Venue enquiry waiting", "Site visit not booked", "Date-sensitive lead going cold"],
    assistantRole: "venue sales front-desk assistant",
    customerMessage: "We are planning a 120-person wedding next October.",
    assistantReply: "Congratulations. I can help check the right package path. Do you already have a preferred October date, and would you like to arrange a venue visit?",
    signalLabels: ["Event", "Date", "Guests"],
  },
  {
    id: "catering",
    label: "Catering",
    aliases: ["catering", "caterer", "catering company"],
    category: "Hospitality & events",
    headline: "Turn catering enquiries into qualified quotes.",
    subheadline: "RevenueDesk captures event type, date, guest count and service needs before your team builds the quote.",
    deskName: "Catering Revenue Desk",
    problem: "Catering quotes depend on several details, but those details are often spread across messages and calls.",
    outcome: "RevenueDesk gets the brief right before your team prices the event.",
    services: ["Corporate catering", "Wedding catering", "Private functions", "Platters", "Event staffing"],
    qualificationQuestions: ["What type of event is it?", "What date is the event?", "How many guests are you catering for?", "Do you need delivery, setup or staffing as well?"],
    urgentKeywords: ["this week", "urgent", "availability", "booking"],
    fitKeywords: ["catering", "food", "platters", "wedding", "event", "conference"],
    leakTypes: ["Quote request waiting", "Date-sensitive enquiry going cold", "Repeat-event opportunity missed"],
    assistantRole: "catering sales front-desk assistant",
    customerMessage: "We need catering for 80 people in Sandton next month.",
    assistantReply: "We can help. What type of event is it, and do you need delivery only or setup and staff as well?",
    signalLabels: ["Event", "Guests", "Service"],
  },
  {
    id: "engineering",
    label: "Engineering / Architecture",
    aliases: ["engineering", "engineer", "architecture", "architect", "quantity surveyor"],
    category: "Professional services",
    headline: "Turn project enquiries into qualified consultations.",
    subheadline: "RevenueDesk captures project type, stage, location and scope before the technical team spends time on a discovery call.",
    deskName: "Project Revenue Desk",
    problem: "Professional firms lose high-value enquiries when partners and engineers are busy with existing projects.",
    outcome: "RevenueDesk captures a useful project brief and routes serious enquiries faster.",
    services: ["Engineering consulting", "Architecture", "Project planning", "Quantity surveying", "Technical studies"],
    qualificationQuestions: ["What type of project is this?", "Where is the project located?", "What stage is the project at?", "What do you need from the technical team?"],
    urgentKeywords: ["tender", "deadline", "submission", "urgent", "project start"],
    fitKeywords: ["engineer", "engineering", "architect", "design", "project", "quantity surveyor"],
    leakTypes: ["Project enquiry waiting", "Tender opportunity not followed up", "Consultation not booked"],
    assistantRole: "professional-services front-desk assistant",
    customerMessage: "We need an engineer for a warehouse development in Midrand.",
    assistantReply: "We can help route this to the right team. What stage is the project at, and what engineering discipline is required?",
    signalLabels: ["Project", "Stage", "Discipline"],
  },
  {
    id: "facilities-fire",
    label: "Facilities / Fire Protection",
    aliases: ["facilities management", "facilities", "fire protection", "fire safety", "fire systems"],
    category: "Commercial services",
    headline: "Turn facilities and compliance enquiries into scheduled work.",
    subheadline: "RevenueDesk qualifies sites, systems, compliance dates and service requirements before a technician or surveyor is dispatched.",
    deskName: "Facilities Revenue Desk",
    problem: "Commercial service teams manage recurring sites, urgent faults and compliance deadlines at the same time.",
    outcome: "RevenueDesk captures site and service context and keeps recurring opportunities visible.",
    services: ["Facilities management", "Fire compliance", "Fire equipment", "Inspections", "Maintenance contracts"],
    qualificationQuestions: ["What type of site is this?", "Which area is the site in?", "Is this a repair, inspection, compliance or maintenance request?", "Is there a deadline or certificate date?"],
    urgentKeywords: ["fire", "alarm", "compliance deadline", "urgent", "inspection", "certificate"],
    fitKeywords: ["facilities", "fire", "compliance", "maintenance", "inspection", "extinguisher"],
    leakTypes: ["Compliance deadline enquiry waiting", "Site inspection not booked", "Maintenance contract opportunity missed"],
    assistantRole: "commercial facilities front-desk assistant",
    customerMessage: "Our fire compliance certificate expires next month.",
    assistantReply: "We can help. What type of site is it, which area is it in, and do you need an inspection, equipment service or certificate renewal?",
    signalLabels: ["Site", "Service", "Deadline"],
  },
];

export function getIndustryExperience(industry: string | null | undefined): IndustryExperience | null {
  const value = (industry ?? "").trim().toLowerCase();
  if (!value) return null;
  return INDUSTRY_EXPERIENCES.find((experience) =>
    value === experience.id ||
    value === experience.label.toLowerCase() ||
    experience.aliases.some((alias) => value === alias || value.includes(alias)),
  ) ?? null;
}

export function getIndustryOptions() {
  return INDUSTRY_EXPERIENCES.map((experience) => ({
    value: experience.label,
    label: experience.label,
    category: experience.category,
  }));
}
