/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedShellRouteRouteImport } from './routes/_authenticated/_shell/route'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedShellAutoReplyRouteImport } from './routes/_authenticated/_shell/auto-reply'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated/_shell/dashboard'
import { Route as AuthenticatedShellInboxRouteImport } from './routes/_authenticated/_shell/inbox'
import { Route as AuthenticatedShellLeadIntentRouteImport } from './routes/_authenticated/_shell/lead-intent'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated/_shell/settings'
import { Route as AuthenticatedShellWebsiteRouteImport } from './routes/_authenticated/_shell/website'
import { Route as ApiPublicSiteLeadRouteImport } from './routes/api/public/site-lead'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiCronLeadLeakageRouteImport } from './routes/api/cron/lead-leakage'
import { Route as ApiTestAcceptanceRouteImport } from './routes/api/test/acceptance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRouteRoute = AuthenticatedShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellAutoReplyRoute =
  AuthenticatedShellAutoReplyRouteImport.update({
    id: '/auto-reply',
    path: '/auto-reply',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellInboxRoute = AuthenticatedShellInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedShellRouteRoute,
} as any)
const AuthenticatedShellLeadIntentRoute =
  AuthenticatedShellLeadIntentRouteImport.update({
    id: '/lead-intent',
    path: '/lead-intent',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellWebsiteRoute =
  AuthenticatedShellWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const ApiPublicSiteLeadRoute = ApiPublicSiteLeadRouteImport.update({
  id: '/api/public/site-lead',
  path: '/api/public/site-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronLeadLeakageRoute = ApiCronLeadLeakageRouteImport.update({
  id: '/api/cron/lead-leakage',
  path: '/api/cron/lead-leakage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestAcceptanceRoute = ApiTestAcceptanceRouteImport.update({
  id: '/api/test/acceptance',
  path: '/api/test/acceptance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/s/$slug': typeof SSlugRoute
  '/auto-reply': typeof AuthenticatedShellAutoReplyRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/inbox': typeof AuthenticatedShellInboxRoute
  '/lead-intent': typeof AuthenticatedShellLeadIntentRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/website': typeof AuthenticatedShellWebsiteRoute
  '/api/public/site-lead': typeof ApiPublicSiteLeadRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/cron/lead-leakage': typeof ApiCronLeadLeakageRoute
  '/api/test/acceptance': typeof ApiTestAcceptanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/s/$slug': typeof SSlugRoute
  '/auto-reply': typeof AuthenticatedShellAutoReplyRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/inbox': typeof AuthenticatedShellInboxRoute
  '/lead-intent': typeof AuthenticatedShellLeadIntentRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/website': typeof AuthenticatedShellWebsiteRoute
  '/api/public/site-lead': typeof ApiPublicSiteLeadRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/cron/lead-leakage': typeof ApiCronLeadLeakageRoute
  '/api/test/acceptance': typeof ApiTestAcceptanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/_shell/auto-reply': typeof AuthenticatedShellAutoReplyRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/inbox': typeof AuthenticatedShellInboxRoute
  '/_authenticated/_shell/lead-intent': typeof AuthenticatedShellLeadIntentRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRoute
  '/_authenticated/_shell/website': typeof AuthenticatedShellWebsiteRoute
  '/api/public/site-lead': typeof ApiPublicSiteLeadRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/cron/lead-leakage': typeof ApiCronLeadLeakageRoute
  '/api/test/acceptance': typeof ApiTestAcceptanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/s/$slug'
    | '/auto-reply'
    | '/dashboard'
    | '/inbox'
    | '/lead-intent'
    | '/settings'
    | '/website'
    | '/api/public/site-lead'
    | '/api/public/whatsapp/webhook'
    | '/api/cron/lead-leakage'
    | '/api/test/acceptance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/s/$slug'
    | '/auto-reply'
    | '/dashboard'
    | '/inbox'
    | '/lead-intent'
    | '/settings'
    | '/website'
    | '/api/public/site-lead'
    | '/api/public/whatsapp/webhook'
    | '/api/cron/lead-leakage'
    | '/api/test/acceptance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_shell'
    | '/_authenticated/onboarding'
    | '/s/$slug'
    | '/_authenticated/_shell/auto-reply'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/inbox'
    | '/_authenticated/_shell/lead-intent'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/website'
    | '/api/public/site-lead'
    | '/api/public/whatsapp/webhook'
    | '/api/cron/lead-leakage'
    | '/api/test/acceptance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicSiteLeadRoute: typeof ApiPublicSiteLeadRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiCronLeadLeakageRoute: typeof ApiCronLeadLeakageRoute
  ApiTestAcceptanceRoute: typeof ApiTestAcceptanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell/auto-reply': {
      id: '/_authenticated/_shell/auto-reply'
      path: '/auto-reply'
      fullPath: '/auto-reply'
      preLoaderRoute: typeof AuthenticatedShellAutoReplyRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/inbox': {
      id: '/_authenticated/_shell/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedShellInboxRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/lead-intent': {
      id: '/_authenticated/_shell/lead-intent'
      path: '/lead-intent'
      fullPath: '/lead-intent'
      preLoaderRoute: typeof AuthenticatedShellLeadIntentRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/website': {
      id: '/_authenticated/_shell/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof AuthenticatedShellWebsiteRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/api/public/site-lead': {
      id: '/api/public/site-lead'
      path: '/api/public/site-lead'
      fullPath: '/api/public/site-lead'
      preLoaderRoute: typeof ApiPublicSiteLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/lead-leakage': {
      id: '/api/cron/lead-leakage'
      path: '/api/cron/lead-leakage'
      fullPath: '/api/cron/lead-leakage'
      preLoaderRoute: typeof ApiCronLeadLeakageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/acceptance': {
      id: '/api/test/acceptance'
      path: '/api/test/acceptance'
      fullPath: '/api/test/acceptance'
      preLoaderRoute: typeof ApiTestAcceptanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedShellRouteRouteChildren {
  AuthenticatedShellAutoReplyRoute: typeof AuthenticatedShellAutoReplyRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellInboxRoute: typeof AuthenticatedShellInboxRoute
  AuthenticatedShellLeadIntentRoute: typeof AuthenticatedShellLeadIntentRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRoute
  AuthenticatedShellWebsiteRoute: typeof AuthenticatedShellWebsiteRoute
}

const AuthenticatedShellRouteRouteChildren: AuthenticatedShellRouteRouteChildren =
  {
    AuthenticatedShellAutoReplyRoute: AuthenticatedShellAutoReplyRoute,
    AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
    AuthenticatedShellInboxRoute: AuthenticatedShellInboxRoute,
    AuthenticatedShellLeadIntentRoute: AuthenticatedShellLeadIntentRoute,
    AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRoute,
    AuthenticatedShellWebsiteRoute: AuthenticatedShellWebsiteRoute,
  }

const AuthenticatedShellRouteRouteWithChildren =
  AuthenticatedShellRouteRoute._addFileChildren(
    AuthenticatedShellRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRouteRoute: typeof AuthenticatedShellRouteRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRouteRoute: AuthenticatedShellRouteRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicSiteLeadRoute: ApiPublicSiteLeadRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiCronLeadLeakageRoute: ApiCronLeadLeakageRoute,
  ApiTestAcceptanceRoute: ApiTestAcceptanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
